cambios
lilmonk3y/agenda_agil pull request #1
Opened 2018-06-20 23:49 UTC by lilmonk3y

Hice un test pelotudo que no sirve para nada. Veanlo

2018-06-20 23:50 UTC, maxicinq commented
Me gusta, no sé qué péro me gusta.

2018-06-20 23:59 UTC, lilmonk3y commented on app/src/test/java/com/devs/agenda_agil/AgendaTest.java
> +    @Test
Capo, que mierda hiciste acá

2018-06-21 00:00 UTC, emiliostropeni commented on app/src/test/java/com/devs/agenda_agil/AgendaTest.java
> +    @Test
nada maestro

2018-06-21 00:00 UTC, maxicinq commented on app/src/test/java/com/devs/agenda_agil/AgendaTest.java
> +    @Test
Capo lo hiciste vos (?

2018-06-21 00:01 UTC, emiliostropeni requested changes
Hasta que no me lo modifiques, no te permito el merge.

2018-06-23 19:53 UTC, closed without merging